/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_rectilineargrid_free(a: number): void;
export function __wbg_texture2d_free(a: number): void;
export function __wbg_triangularmesh_free(a: number): void;
export function texture2d_fill_canvas(a: number, b: number, c: number, d: number, e: number): void;
export function rectilineargrid_new(a: number, b: number): number;
export function rectilineargrid_draw(a: number, b: number, c: number, d: number, e: number): void;
export function rectilineargrid_mark(a: number, b: number, c: number): number;
export function rectilineargrid_clear(a: number): void;
export function rectilineargrid_animation_frame(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function triangularmesh_new(a: number, b: number, c: number, d: number): number;
export function triangularmesh_draw(a: number, b: number, c: number, d: number, e: number): void;
export function triangularmesh_animation_frame(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function triangularmesh_mark(a: number, b: number): number;
export function triangularmesh_clear(a: number): void;
export function draw_hex_grid(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_cursorstate_free(a: number): void;
export function __wbg_cursor_free(a: number): void;
export function cursor_new(): number;
export function cursor_keyring(a: number, b: number, c: number, d: number, e: number): void;
export function cursor_ticks(a: number, b: number, c: number, d: number, e: number): void;
export function cursor_draw(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function __wbg_spring_free(a: number): void;
export function __wbg_get_spring_x(a: number): number;
export function __wbg_set_spring_x(a: number, b: number): void;
export function spring_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function spring_potential_energy(a: number): number;
export function spring_force(a: number): number;
export function spring_drop(a: number): number;
export function spring_update(a: number, b: number): void;
export function spring_size(a: number, b: number): number;
export function __wbg_link_free(a: number): void;
export function link_new(a: number): number;
export function __wbg_agent_free(a: number): void;
export function agent_new(a: number, b: number, c: number): number;
export function agent_push_link(a: number, b: number): void;
export function agent_clamp_motion(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function agent_draw_agent(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): void;
export function __wbg_group_free(a: number): void;
export function group_new(): number;
export function random_series(a: number, b: number): void;
export function __wbg_axis_free(a: number): void;
export function __wbg_observation_free(a: number): void;
export function __wbg_observedproperty_free(a: number): void;
export function __wbg_datastream_free(a: number): void;
export function datastream_new(a: number): number;
export function datastream_push(a: number, b: number, c: number): void;
export function datastream_draw(a: number, b: number, c: number, d: number, e: number): void;
export function panic_hook(): void;
export function create_color_map_canvas(a: number): number;
export function clear_rect_blending(a: number, b: number, c: number, d: number): void;
export function draw_fps(a: number, b: number, c: number, d: number): number;
export function draw_caption(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function draw_single_pixel(a: number, b: number, c: number, d: number, e: number): void;
export function alloc(a: number): number;
export function dealloc(a: number, b: number): void;
export function fetch_text(a: number, b: number): number;
export function make_vertex_array(a: number, b: number, c: number): void;
export function mouse_move(a: number, b: number): void;
export function create_program(a: number, b: number, c: number, d: number, e: number): number;
export function create_buffer(a: number, b: number, c: number): number;
export function bind_texture(a: number, b: number, c: number): void;
export function create_texture(a: number, b: number, c: number, d: number, e: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9a9f3efc86f4423b(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hc5676375af21edd9(a: number, b: number, c: number, d: number): void;
